name: source_gen_example
publish_to: none
resolution: workspace

environment:
  sdk: ^3.7.0

dependencies:
  analyzer: '>=7.4.0 <8.0.0'
  build: ^3.0.0
  source_gen: any

dev_dependencies:
  dart_flutter_team_lints: ^3.1.0
