name: source_gen_example
publish_to: none
resolution: workspace

environment:
  sdk: ^3.7.0

dependencies:
  build: ^3.0.0-dev
  source_gen: any
  analyzer: ^7.4.0

dev_dependencies:
  dart_flutter_team_lints: ^3.1.0
