name: source_gen_example

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  analyzer: '>=0.42.0-nullsafety <2.0.0'
  build: ^2.0.0
  source_gen: any

dependency_overrides:
  # todo: Remove dart_style override before merging
  dart_style:
    git:
      url: git@github.com:dart-lang/dart_style.git
  source_gen:
    path: ../source_gen
