name: source_gen_example
publish_to: none
resolution: workspace

environment:
  sdk: ^3.7.0

dependencies:
  analyzer: '>=8.1.1 <9.0.0'
  build: '>=3.0.0 <5.0.0'
  source_gen: any

dev_dependencies:
  dart_flutter_team_lints: ^3.1.0
