name: source_gen_example_usage

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dev_dependencies:
  build_runner: ^1.12.0
  build_verify: ^1.1.0
  source_gen_example:
    path: ../example
  test: ^1.16.0

dependency_overrides:
  # Temporarily necessary until build_runner supports the latest version
  dart_style: ^2.0.0
  source_gen:
    path: ../source_gen
