name: source_gen_example_usage

environment:
  sdk: '>=2.0.0 <3.0.0'

dev_dependencies:
  build_runner: ^1.0.0
  source_gen_example:
    path: ../example

dependency_overrides:
  source_gen:
    path: ../source_gen
