# See https://github.com/dart-lang/mono_repo for details
dart:
  - dev
  - 2.0.0

stages:
  - analyze_format:
    - group:
        - dartfmt
        - dartanalyzer: --fatal-infos --fatal-warnings .
  - unit_test:
    - test:

cache:
  directories:
    - .dart_tool/build
