name: source_gen_test
version: 0.1.0-dev
description: >-
  Test support for the source_gen package.
  Includes helpers to make it easy to validate both success and failure cases.
homepage: https://github.com/dart-lang/source_gen

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  analyzer: '>=0.33.3 <0.36.0'
  build: '>=0.12.6 <2.0.0'
  build_test: ^0.10.0
  dart_style: ^1.2.0
  meta: ^1.0.2
  path: ^1.3.2
  source_gen: ^0.9.5
  test: ^1.3.3

dependency_overrides:
  source_gen:
    path: ../source_gen
