# A CI configuration to auto-publish pub packages.

name: Publish

on:
  pull_request:
    branches: [ master ]
  push:
    tags: [ '[A-z]+-v[0-9]+.[0-9]+.[0-9]+*' ]

jobs:
  publish:
    if: ${{ github.repository_owner == 'dart-lang' }}
    uses: dart-lang/ecosystem/.github/workflows/publish.yaml@main
    permissions:
      contents: read # You might already have this, but it's good practice
      pull-requests: write # Add this line
      id-token: write # Add this line